# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Safira
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: "Check if has insomnia workspace"
        id: check_inso_workspace
        uses: andstor/file-existence-action@v1
        with:
         files: ".insomnia/ApiSpec/spc_*.yml"
      
      - name: Exporting openapi from insomnia workspace
        if: steps.check_inso_workspace.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: |
          npx insomnia-inso export spec "$(cat .insomnia/ApiSpec/spc_*.yml | yq '.fileName')"  --output openapi-swagger.yaml
          cat openapi-swagger.yaml

          

