# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Safira
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: "Check if has insomnia workspace"
        id: check_inso_workspace
        uses: andstor/file-existence-action@v1
        with:
         files: ".insomnia"
         
      - name: install insomnia inso
        if: steps.check_inso_workspace.outputs.files_exists == 'true'
        run: |
          npm i -g insomnia-inso@latest
          echo "Isomnia version: $(inso --version)"
      
      - name: Insomnia exists?
        if: steps.check_inso_workspace.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo insomnia exists!

          

